MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/mnt/ssd8tb/quang/pretrain/jx_vit_base_p16_224-80ecf9dd.pth'
  PRETRAIN_NAME: 'jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  Transformer_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [14, 14]
  COS_LAYER: False
  CAMERA_EMBEDDING: False
  VIEWPOINT_EMBEDDING: False
  LOCAL_F: False
  AIE_COE: 2.5
  DROP_PATH : 0.1
  ID_LOSS_TYPE: "N"
INPUT:
  # SIZE_TRAIN: [224, 224]
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: 'veri'
  ROOT_DIR: /mnt/Data/dataset/ReiD/
  # ROOT_DIR: /mnt/ssd8tb/quang/
  LABEL_FOLDER: 'outputs/tracking_results'
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  # BASE_LR: 0.01
  BASE_LR: 0.0001
  IMS_PER_BATCH: 64
  STEPS: [20, /home/synh/workspace/quang/Multi-Camera-People-Tracking/outputs35]
  GAMMA: 0.
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 70
  LOG_PERIOD: 200
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  FP16_ENABLED: True
  WARMUP_METHOD: CosineAnnealing
  SEED: 507
  IMS_PER_BATCH: 96
  EVAL_PERIOD: 4
# SOLVER:
#   OPTIMIZER_NAME: 'Adam'
#   MAX_EPOCHS: 120
#   BASE_LR: 0.00035
#   # BASE_LR: 0.1
#   MOMENTUM: 0.9
#   CLUSTER_MARGIN: 0.3

#   CENTER_LR: 0.5
#   CENTER_LOSS_WEIGHT: 0.0005

#   RANGE_K: 2
#   RANGE_MARGIN: 0.3
#   RANGE_ALPHA: 0
#   RANGE_BETA: 1
#   RANGE_LOSS_WEIGHT: 1

#   BIAS_LR_FACTOR: 1
#   WEIGHT_DECAY: 0.0005
#   WEIGHT_DECAY_BIAS: 0.0005
#   IMS_PER_BATCH: 64

#   STEPS: [5, 10, 15, 20, 25, 30]
#   GAMMA: 0.1

#   WARMUP_FACTOR: 0.01
#   WARMUP_ITERS: 0
#   WARMUP_METHOD: 'linear'

#   CHECKPOINT_PERIOD: 40
#   LOG_PERIOD: 20
#   EVAL_PERIOD: 3
#   SEED: 507

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: False
  RE_RANKING_TRACK: FALSE
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
  EVAL: True
  FIC: True

OUTPUT_DIR: "./ouptut"
CHECKPOINT_PATH: "output/transformer/epoch=7-Val_CMC@rank1=0.97848-Val_CMC@rank5=0.99139.ckpt"